### ISSUE TITLE
AssertionError: dim of adj does not match the num of sent, where the idx is 53

### ISSUE THREAD

**Issue by NEXUS-Liu** [ytc272098215/FakeNewsDetection#13]
Traceback (most recent call last):
  File "main.py", line 144, in <module>
    main(params)
  File "main.py", line 106, in main
    dl = DataLoader(params)
  File "/root/rumor/CompareNet_FakeNewsDetection-master/CompareNet_FakeNewsDetection-master/data_loader.py", line 84, in __init__
    dataset_train = DataSet(self.train, self.adj_train, self.fea_train, self.params, self.entity_description)
  File "/root/rumor/CompareNet_FakeNewsDetection-master/CompareNet_FakeNewsDetection-master/data_loader.py", line 266, in __init__
    "dim of adj does not match the num of sent, where the idx is {}".format(i)
AssertionError: dim of adj does not match the num of sent, where the idx is 53
感谢您的分享，请问这个问题应该如何解决呢？

**Comment by thiagoalvesl** [comment]
Same problem here. Did you find a solution?
