### ISSUE TITLE
AssertionError: dim of adj does not match the num of sent, where the idx is 5

### ISSUE THREAD

**Issue by wenjtop** [ytc272098215/FakeNewsDetection#7]
Thank you for sharing your source code. I had an issue when I ran the source code. Could you please tell me what is the problem?

`Traceback (most recent call last):
  File "main.py", line 142, in <module>
    main(params)
  File "main.py", line 104, in main
    dl = DataLoader(params)
  File "D:\taobao\twitter\CompareNet_FakeNewsDetection-master\CompareNet_FakeNewsDetection-master\data_loader
.py", line 84, in __init__
    dataset_train = DataSet(self.train, self.adj_train, self.fea_train, self.params, self.entity_description)

  File "D:\taobao\twitter\CompareNet_FakeNewsDetection-master\CompareNet_FakeNewsDetection-master\data_loader
.py", line 263, in __init__
    assert a[0].shape[0] == len(self.sents[i]),\
AssertionError: dim of adj does not match the num of sent, where the idx is 5
`

**Comment by Xiang-Pan** [comment]
Same issue, solved by changing the NLTK to version 3.2.5 as required.
